### ISSUE TITLE
Feature labels are duplicated if they end at the last base

### ISSUE THREAD

**Issue by iimog** [AliTVTeam/AliTV#131]
If a feature ends at the last base of the chromosome its label is duplicated and displayed at the beginning of the sequence as well. This is probably the case because AliTV considers the sequence circular and the last base is also the 0th base. However this behavior is not desired.
To reproduce this problem you can use those snippets:

`test.fa`
```
>test
ACGTACGTAC
```

`test.tsv`
```
test	1	4	-1	A
test	7	10	-1	B
```

`test.yml`
```
genomes:
    -
        name: test
        sequence_files:
            - test.fa
        feature_files:
            test:
                - test.tsv
    -
        name: test clone
        sequence_files:
            - test.fa
        feature_files:
            test:
                - test.tsv
```

and executing

```bash
perl alitv.pl test.yml
```
